version: "3.2"
services:
  postgres:
    image: postgres
    restart: always
  sample-server:
    image: uchqun/sample-server
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    ports:
    - "8082:8082"
  sample-client:
    image: uchqun/sample-client
    command: npm run dev
    ports:
    - "8080:8080"